### ISSUE TITLE
Depth unit question

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [vrmarcelino/CCMetagen#11]
Hi,
For the kma depth unit, it is not clear what is meant by 'template' and 'overlapping the template'. Does this mean, the number of nucleotides of all kmers of the read that align to the template? And is 'template' the entire nt entry, e.g. it could be a whole chromosome? Or is 'template' the sequence aligned to the read from the db? Can you please clarify? I can see that the definitions are similar to those used in RNAseq but might not be appropriate for metagenomics because the 'template' is not a descrete gene or transcript.

Thanks,

Theo

**Comment by theo-allnutt-bioinformatics** [comment]
In additon - is there a way to obtain the number of reads classified to a taxon instead of the 'abundance'?

Sorry for so many questions!

**Comment by vrmarcelino** [comment]
Hi Theo!

We used the definitions consistent with the ones used in KMA. So template is the reference sequence, it is just a more neutral term that applies for genes, CDS, gene fragments, etc.
The number of bases overlapping the template (coverage) is the number of nucleotides overlapping the reference sequence. This is more accurate than using the number of reads (as reads may only partially overlap the template, when they align to their edges). 
Yes, the length of the sequence can be a whole chromosome if that is in the database.
And yes, you can use the flag ‘--depth_unit rpm’ to have the Reads Per million.
You can also use ‘--depth_unit nc’ to just count the number of nucleotides mapping to each template (divide that by read length to get the number of reads).
Hope this makes sense.
