### ISSUE TITLE
suggestion: merge species but not files

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [vrmarcelino/CCMetagen#12]
Hi,

it would be useful to be able to output results for a taxonomic level for each .csv in a results directory, but not merge the samples (files). Currently with CCMetagen_merge.py I ahve to put the .csv results each in a separate directory.

Thanks,

Theo

**Comment by theo-allnutt-bioinformatics** [comment]
I also note that when using ' -t Species' the output also includes taxa with no species classification, e.g.
3.65 | Bacteria | unk_k | Actinobacteria | Actinobacteria | Corynebacteriales | Mycobacteriaceae | Mycobacterium

**Comment by vrmarcelino** [comment]
Hi!

I am not sure I understand the first question. You can specify the output directory with -o (so -o <dir_path/file_path>. Was this the issue? 
The last version of CCMetagen can also deal with other .csv files in the input folder (as long as they are not names ".res.csv".

**Comment by vrmarcelino** [comment]
Regarding your second question - this is actually done on purpose: without this feature, when you run CCMetagen in samples were most species are unknown, you end up with a skewed species table (containing only the taxa classified at species level). It is easy to delete (or rename as 'unclassified') these taxa from the merged.csv file, and it is convenient to know the proportion of taxa that were not classified at that level.

**Comment by theo-allnutt-bioinformatics** [comment]
It would be more convenient if they were all summed into 'unclassified'.

With respect to the first question,  CCMetagen_merge.py merges all samples (separeate .csvs) into one table, which normally is fine, but it would also be useful to output each sample separately for each taxonomic level specified. 

Thanks.
