### ISSUE TITLE
Classified/Unclassified Reads

### ISSUE THREAD

**Issue by punnettsun** [vrmarcelino/CCMetagen#15]
Hello,

Is there a way to see which query reads were left unclassified with "unknown taxa". I understand that certain query sequences can be left as "none" if the sequence similarity is below a certain threshold. If there are reads left unclassified at all levels, how would I be able to know which query reads they came from? Is this possible?

Thank you.

**Comment by vrmarcelino** [comment]
Hi Punit!

CCMetagen does not have this functionality, but you can find out which sequences were classified, and then compare that with the original sequences (using grep for example).

To see which sequences were classified, you can either use CCMetagen_extract_seqs.py (gets the sequences after filtering), or inspect the KMA output file with the .frag extension.

**Comment by punnettsun** [comment]
Great, thank you!
