### ISSUE TITLE
multiple lanes (paired end) for each sample

### ISSUE THREAD

**Issue by molbio7** [vrmarcelino/CCMetagen#17]
Hi,

What should be the command for multiple lanes for each sample? for example for under sample5 directory, we have:

sample5_L3_1.fq.gz
sample5_L3_2.fq.gz
sample5_L4_1.fq.gz
sample5_L3_2.fq.gz

Should we pool R1 and R2 files together or just use comma separated files in the command line?

Any advice please?
thanks

**Comment by vrmarcelino** [comment]
Hi there!

From the KMA manual <https://bitbucket.org/genomicepidemiology/kma/src/master/KMAspecification.pdf>:
Multiple files can be passed to -ipe by adding them next to each other (separated by space)
Just make sure that file pairs are kept next to each other.
