### ISSUE TITLE
Custom Database 

### ISSUE THREAD

**Issue by punnettsun** [vrmarcelino/CCMetagen#18]
Hello,

If I didn't want to use NCBI and wanted to use my own database to classify sequences, would I be able to do it with CCMetagen? I have my own IDs and taxonomy. Would CCMetagen still work or would it only work by having NCBI databases and taxonomy?

Thank you.

**Comment by vrmarcelino** [comment]
Hi!

Are your IDs the NCBI taxids? CCMetagen requires the NCBI taxids, which can be obtained for any taxa. These taxids need to be in the sequence header, followed by a "|", ex:
>1485|Clostridium sp. 
If you don't have the NCBI taxids, I have a python script that infers the taxids based on species names, happy to share if you think it will be useful.

**Comment by punnettsun** [comment]
Some of the IDs are NCBI taxids but some are not. 
Your python script will definitely help if you can send it to me! Thank you so much.

**Comment by vrmarcelino** [comment]
Hi!

Check the script attached (must rename from .txt to .py).
It takes as input a txt file with species (or genus) names and tries to get the taxids.
The input text file should have one taxon per line.
I noticed that it does not find the taxid when the genus name is in brackets (e.g. [Clostridium] innocuum), so the results will need a manual check.

[get_lineages_and_taxids_from_sp_names.txt](https://github.com/vrmarcelino/CCMetagen/files/5216285/get_lineages_and_taxids_from_sp_names.txt)

Hope this helps!
