### ISSUE TITLE
Obtaining RPM, fragments, and proportion of mapper reads

### ISSUE THREAD

**Issue by Tj-Idowu** [vrmarcelino/CCMetagen#21]
I followed the quick start for the running kma and added the -ef flag to get the extended features but the results did not show any columns pertaining to the number of reads.

`kma -ipe forward_1.fastq reverse_2.fastq -o output -t_db reference -1t1 -mem_mode -and -apm f -ef`

**Comment by vrmarcelino** [comment]
Hi!

This should generate an additional file (extension .mapstat). Did you get that?

**Comment by Tj-Idowu** [comment]
Thank you
