### ISSUE TITLE
rename_nt.py is not considering multi seq IDs in fasta headers

### ISSUE THREAD

**Issue by mihkelvaher** [vrmarcelino/CCMetagen#24]
Hi!
Looking at the results I encountered some really long fasta headers:
`399742|LK006623.1 TPA: Enterobacter sp. 638 tRNA-Tyr-GTA-2-1 gene^ALK006624.1 TPA: Enterobacter sp. 638 tRNA-Tyr-GTA-2-2 gene^AL
K006813.1 TPA: Escherichia coli 536 tRNA-Tyr-GTA-2-1 gene^ALK006814.1 TPA: Escherichia coli 536 tRNA-Tyr-GTA-2-2 gene^ALK006909.
1 TPA: Escherichia coli APEC O1 tRNA-Tyr-GTA-2-1 gene^ALK006910.1 TPA: Escherichia coli APE`

NCBI uses a sort of a "multi-header" for identical sequences, sequence IDs are separated with "\x01". In many cases all of the sequences/headers have that same organism (taxid) but sometimes they differ, making the added taxid incorrect for some sequences. This can lead to false positive results.
Kraken2 has solved the situation [here](https://github.com/DerrickWood/kraken2/blob/84b2874e0ba5ffc9abaebe630433a430cd0f69f4/scripts/scan_fasta_file.pl#L32).

**Comment by vrmarcelino** [comment]
Yes, this can happen if identical templates are provided.
We'll look into removing those in future databases. For the time being, one solution would be to detect and remove those before indexing the database.
