### ISSUE TITLE
Issue installing libz-dev

### ISSUE THREAD

**Issue by qfaber** [vrmarcelino/CCMetagen#27]
When I install libz-dev it installs zlib1g-dev

**sudo apt-get install libz-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'zlib1g-dev' instead of 'libz-dev'
zlib1g-dev is already the newest version (1:1.2.11.dfsg-0ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 186 not upgraded.**

kma seems to download fine, but I have an issue with the next step

**git clone https://bitbucket.org/genomicepidemiology/kma.git
Cloning into 'kma'...
Receiving objects: 100% (1325/1325), 2.79 MiB | 9.89 MiB/s, done.
Resolving deltas: 100% (925/925), done.

cd kma && make
/home/racheljoyce/miniconda3/bin/x86_64-conda_cos6-linux-gnu-cc -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -std=c99 -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -c -o align.o align.c
/home/racheljoyce/miniconda3/bin/x86_64-conda_cos6-linux-gnu-cc -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -std=c99 -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -c -o alnfrags.o alnfrags.c
In file included from alnfrags.h:24:0,
                 from alnfrags.c:23:
filebuff.h:21:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
<builtin>: recipe for target 'alnfrags.o' failed
make: *** [alnfrags.o] Error 1**

Any suggestions for how to fix this? Thanks!

**Comment by vrmarcelino** [comment]
Hi!

Can you post this issue in the KMA page?
https://bitbucket.org/genomicepidemiology/kma/issues?status=new&status=open

Thanks!
