### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'NW_001849834.1

### ISSUE THREAD

**Issue by MjelleLab** [vrmarcelino/CCMetagen#30]
Hi,
 I am using the `refseq_bf`  database, and I get the following error when running CCMetagen:

`ValueError: invalid literal for int() with base 10: 'NW_001849834.1
`
command: 
`python ~/software/CCMetagen/CCMetagen/CCMetagen.py -i $FILE.kma.res -o $FILE.CCMetagen.results
`
kma works as expected.

**Comment by vrmarcelino** [comment]
Hi!

I will try to reproduce this error. Could you let me know which version of CCMetagen are you using?

Thanks!

**Comment by MjelleLab** [comment]
> Hi!
> 
> I will try to reproduce this error. Could you let me know which version of CCMetagen are you using?
> 
> Thanks!

I have  v1.3.0

**Comment by vrmarcelino** [comment]
Hi,

I get a similar error when forgetting to add the '-r RefSeq' flag when running CCMetagen with this database. The default expects the NCBI nt format.

Could that be the issue for you?
