### ISSUE TITLE
kma error 2

### ISSUE THREAD

**Issue by vasudhajain29** [vrmarcelino/CCMetagen#32]
Hi 
I am trying to run following command:
```
kma -t 15 -ipe Sample1_R1.fastq.gz Sample1_R2.fastq.gz -o Sample1_kma -t_db path/to/ncbi_nt_kma/
```

And getting error:
```
Filename:	path/to/ncbi_nt_kma/.length.b
Error: 2 (No such file or directory)
```

Can you please help me understand what this could be related to?

**Comment by vrmarcelino** [comment]
Hi!

It is not finding the database file. If the database is called 'ncbi_nt_kma', then removing the last '/' should work.

You should provide the file path + the basename of the database file.

**Comment by vasudhajain29** [comment]
I made a few changes in the command:
```
kma -t 8 -ipe Sample_R1.fastq.gz Sample_R2.fastq.gz -o path/to/output -t_db /ncbi_nt/ncbi_nt -verbose -mem_mode -and -apm f
```
But now the command is getting killed and showing:
```
killed: 9
```

Also, I am not able to see any log files. Just 4 files are generated: out.aln, out.frag.gz, ouot.fsa, out.res. and all of them are empty.

How can I optimise the RAM usage by kma?

**Comment by vrmarcelino** [comment]
How much memory do you have available?
Besides using the --mem_mode, which you are already doing, you can optimise usage by constructing your own database with a larger prefix.

**Comment by vasudhajain29** [comment]
i have installed my db in a hard disk, where I have approx 4TB memory available.
my laptop has 16Gb RAM.

Is the ncbi_nt_no_env_11jun2019.zip a smaller db?

**Comment by vasudhajain29** [comment]
and can you share a link to ncbi_nt_no_env_11jun2019.zip? I cant find it in the link provided.

**Comment by vrmarcelino** [comment]
Hi,

I think 4TB is your disk space. 16Gb is not enough to run KMA with the NCBI collection. You will need to use a server with at least 250Gb of RAM. If that is not an option, the only classifier I'm aware of that can run on a laptop is Centrifuge.

**Comment by vasudhajain29** [comment]
Ok..thank you for your suggestion. 
i'll look into it.

**Comment by Najmabms** [comment]
Hi,
I am having the same issue. I run this command and the result was the same error:
kma -ipe ~/path/to/sample_R1_001.fastq.gz ~/path/to/sample_R2_001.fastq.gz -o ~/path/to/sample_out_kma -t_db /path/to/nt -t 8 -1t1 -mem_mode -and -apm f

I am running on a server with 125Gb RAM and 120Gb space. These are the resources allocated for me. I am not sure how to resolve the issue.
Help is appreciated

**Comment by Najmabms** [comment]
I forgot to mention that these are the resources allocated for me.
I am running on a server with 125Gb RAM and 120Gb space

**Comment by vrmarcelino** [comment]
Hi!

You will need more memory (~500Gb RAM) and space to run the analysis with the NCBI database.
If that is not feasible, you could use the webserver:

https://cge.food.dtu.dk/services/CCMetagen/
