### ISSUE TITLE
Database download problem

### ISSUE THREAD

**Issue by AMPByrne** [vrmarcelino/CCMetagen#33]
Hi, I've been trying to download the pre-indexed databases from you cloudstor website (https://cloudstor.aarnet.edu.au/plus/s/vfKH9S8c5FVGBjV) but the download keeps either stalling or failing at around 40-60 Gb.  

I have tried downloading the hole package and individual files using both via firefox and wget, but get the same problem.

Do you know of any potential solution?

**Comment by vrmarcelino** [comment]
Hi!

I did not manage to reproduce the problem, but maybe cloudstor was offline for a while.
I would recommend using wget and downloading one file a time. If it fails, you can resume the download by passing the -c flag:

Ex:
`wget -c 'https://cloudstor.aarnet.edu.au/plus/s/vfKH9S8c5FVGBjV/download?path=%2F&files=ncbi_nt_no_env_11jun2019.zip'`

Hope it helps!
