### ISSUE TITLE
ValueError: 1327640 taxid not found

### ISSUE THREAD

**Issue by taniagmangolini** [vrmarcelino/CCMetagen#34]
I am getting the following error:

2022-02-23T18:31:46.257-03:00	match_info = fNCBItax.lineage_extractor(match_info.TaxId, match_info, taxfile)
2022-02-23T18:31:46.257-03:00	File "/usr/local/lib/python3.9/site-packages/ccmetagen/fNCBItax.py", line 24, in lineage_extractor
2022-02-23T18:31:46.257-03:00	lineage = ncbi.get_lineage(query_taxid)
2022-02-23T18:31:46.257-03:00	File "/usr/local/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 241, in get_lineage
2022-02-23T18:31:46.258-03:00	raise ValueError("%s taxid not found" %taxid)
2022-02-23T18:31:46.258-03:00   ValueError: 1327640 taxid not found ValueError: 1327640 taxid not found

According to the NCBI this taxon 132640 was deleted, but probably it exists in the ccmetagen database I am using...

How CCmetagen should deal with taxons not found in the updated taxonomy dump?

**Comment by taniagmangolini** [comment]
A more complete stacktrace:

Requirement already satisfied: pandas in /usr/local/lib/python3.9/site-packages (1.3.3)
Collecting pandas
  Downloading pandas-1.4.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/site-packages (from pandas) (2021.1)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.9/site-packages (from pandas) (1.21.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Installing collected packages: pandas
Successfully installed pandas-1.4.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
./XXX.kmaout.mapstat
./XXX.kmaout.res
Fasta: .XXX.kmaout.mapstat
./XXX.kmaout.res
processing reads...
NCBI database not present yet (first time used?)
Downloading taxdump.tar.gz from NCBI FTP site (via HTTP)...
Done. Parsing...
Loading node names...
2401818 names loaded.
264211 synonyms loaded.
Loading nodes...
2401818 nodes loaded.
Linking nodes...
Tree is loaded.
Updating database: /root/.etetoolkit/taxa.sqlite ...
[...]
Inserting taxids:       2365000 
Inserting taxids:       2370000 
Inserting taxids:       2375000 
Inserting taxids:       2380000 
Inserting taxids:       2385000 
Inserting taxids:       2390000 
Inserting taxids:       2395000 
Inserting taxids:       2400000 Traceback (most recent call last):
  File "/usr/local/bin/CCMetagen.py", line 274, in <module>
    df = fParseKMA.populate_w_tax(df, ref_database, st, gt, ft, ot, ct, pt)
  File "/usr/local/lib/python3.9/site-packages/ccmetagen/fParseKMA.py", line 104, in populate_w_tax
[...]
Uploading to /root/.etetoolkit/taxa.sqlite
Reading file /tmp/scratch/XXX.kmaout.res
Calculating RPM...
           Note 1: to calculate RPM, you need to generate the mapstat file when
           running KMA (flag -ef), and use it as input in CCMetagen (flag --mapstat).
           
           Note 2: you might want to adjust the minimum depth (-d) value accordingly.
           The default minimum depth is 0.2.
           
    match_info = fNCBItax.lineage_extractor(match_info.TaxId, match_info, taxfile)
  File "/usr/local/lib/python3.9/site-packages/ccmetagen/fNCBItax.py", line 24, in lineage_extractor
    lineage = ncbi.get_lineage(query_taxid)
  File "/usr/local/lib/python3.9/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 241, in get_lineage
    raise ValueError("%s taxid not found" %taxid)
ValueError: 1327640 taxid not found

**Comment by vrmarcelino** [comment]
Hi! 
Sorry for late reply.
This is a sign that your local ete3 database needs to be updated (see our FAQ).
Within python, try this:

```
from ete3 import NCBITaxa
ncbi = NCBITaxa()
ncbi.update_taxonomy_database()
```

**Comment by taniagmangolini** [comment]
Thanks for the reply, I am going to try this, but according to the log there wasn't a local ETE database yet because a new database was downloaded:

NCBI database not present yet (first time used?)
Downloading taxdump.tar.gz from NCBI FTP site (via HTTP)...
Done. Parsing...
