### ISSUE TITLE
Read error in KMA Mapping

### ISSUE THREAD

**Issue by tuck82er** [vrmarcelino/CCMetagen#37]
Hi vrmarcelino,

Thanks for putting together CCMetagen! I'm excited to get it working, but have run into an error with kma mapping of my reads. I've followed your guide for creating a custom nt_database, simply using a more up to date version of the database. However, I'm encountering issues with a "Reading error" in the KMA index mapping step.

Another, possibly related issue is that the length.b file gets created, but is empty upon completion of indexing. Maybe this indicates that it didn't complete properly? The outputs I get for indexing include the ".length.b", ".name", and ".seq.b" files. But I'm not seeing any errors etc. I've used the default settings here for the kma indexing:

```
kma index -i NCBI_nt_2022_05_04/nt_w_taxid.fas.gz -o NCBI_nt_2022_05_04/kma/nt_2022_05_04_indexed -NI
```

Then, when running kma mapping I get the following error:

> Reading error. 

```
kma -ipe C_M6_*.trimmed.fastq.gz -t_db NCBI_nt_2022_05_04/kma/nt_2022_05_04_indexed -o C_M6_out_kma -t 24 -1t1 -mem_mode -and -apm f
```

I suspect the empty length.b output above may be leading to the reading error, but am not completely sure.

**Comment by vrmarcelino** [comment]
Hi!

You are right, if length.b file is empty the indexing didn't complete. I suspect that it run our of memory, how much mem do you have available? 
Can you try the index step with the additional flag '-Sparse TG' ?

Thanks!

**Comment by tuck82er** [comment]
Thanks for your response! I've added the '-Sparse TG' flag and am running it now. Will give an update when that finishes. I was using 400GB this past run without that flag. I've bumped it up to 700GB for this next attempt just in case. Initially when I ran it I didn't get the typical 'reached memory limit' error log so the memory issue was not immediately apparent.

Also, having looked at the kma indexing script it does seem like the .length.b file is generated before indexing, but only populated after indexing, so it makes sense that if the process were killed during indexing that this file would be blank.

**Comment by vrmarcelino** [comment]
Thanks!
Let us know how did it go, 700GB should be enough if you use the -Sparse flag.

**Comment by tuck82er** [comment]
Using 1000GB for the memory did the trick regarding my last inquiry! Thank you!

However, I'm now encountering an issue of excessively long runtimes. From some rough calculations there are 81.7 million sequences and it appears only 2.7 million have been hashed. That's about 3.3% in 22 days, so assuming a linear rate the job would take almost 2 more years to complete! Do you have any suggestions for how to improve the runtime? Also, how long did indexing take for you with the 2018 index? 

The current uncompressed nt_w_taxid.fas I am using, from 5-6-2022, is about 700GB.

`kma index -i /home/etucker5/miniconda3/envs/S-niv-MAGs/data/databases/NCBI_nt_2022_05_04/nt_w_taxid.fas.gz -o /home/etucker5/miniconda3/envs/S-niv-MAGs/data/databases/NCBI_nt_2022_05_04/kma/nt_2022_05_04_indexed -NI -Sparse TG -batch`

Edit/Update: A couple differences that may have affected the runtime are using a compressed fas.gz and using the -batch flag. I've removed these and run a "time to solution" and seem to be processing about 20GB per 3 hours. Again, if that stays linear, which it should because kma_index is using hash mapping, then it should finish in a few days, rather than a couple years!

In the meantime I will attempt to use the index you created in 2018 for mapping my sequences. Thanks again!

**Comment by ptlcc** [comment]
Hi Tucker

The "-batch" option is for giving the fasta files in a flat text file, so that does not help here. A speedup could be achieved by adding the "-ME" flag. This will preallocate for the maximum amount of k-mers in the database, which it will end up at anyway with a fasta file that size.
We managed to index the database in one or two days back in 2018, but I imagine it will take somewhat longer today. Unfortunately, there have not been any smart updates to the indexing since.

Best,
Philip
