### ISSUE TITLE
no HTML file produced

### ISSUE THREAD

**Issue by Tj-Idowu** [vrmarcelino/CCMetagen#4]
When I run CCMetagen there is no .html file produced from Krona. Instead I get an empty .tsv file.
This is the message I get:
`Reading file Control/Mapped/P_aeruginosa/FCHLCGNBBXX_L3_wHAXPI058879-108.res
csv file saved as Control/Mapped/P_aeruginosa/FCHLCGNBBXX_L3_wHAXPI058879-108.csv
/bin/sh: 1: ktImportText: not found
krona file saved as Control/Mapped/P_aeruginosa/FCHLCGNBBXX_L3_wHAXPI058879-108.html`

**Comment by vrmarcelino** [comment]
Hi,
I'll need a bit more information. Did you get taxonomic assignments in the .csv file?
And can you please verify that ktImportText (from krona tools) is available in your $PATH? If you type `ktImportText`, do you get a help text?

**Comment by Tj-Idowu** [comment]
Thank you that fixed the error. I added Krona/bin to my $PATH and I don't get that error any more. I am getting a new error though.
`Traceback (most recent call last):
  File "CCMetagen/CCMetagen.py", line 220, in <module>
    subprocess.run(shell_command, shell=True)
AttributeError: 'module' object has no attribute 'run'`

Can you please help me with this? Thank you.

**Comment by vrmarcelino** [comment]
Okay, good.
Which is your version of Python? CCMetagen requires version 3.6, so please check if you have that.

**Comment by Tj-Idowu** [comment]
Thanks for that. My default python setting is 2.7. I put python3 before CCMetagen.py and it worked. Thank you.
