### ISSUE TITLE
Something Error of KMA

### ISSUE THREAD

**Issue by TaoCheng98** [vrmarcelino/CCMetagen#42]
Hi！
When I was ready to use ccMetagen, I found that I had some problems.
At first, after configuring the database, I used rush to parallel kma. It didn't give an error, but it didn't generate any data either. The result files were empty.
I then tried to abandon parallelism, but CCMetagen didn't work because of the "Uneven number of paired end files". I tried to detect my sequence file. In fact, R1 and R2 share the same number of reads. So I don't understand this error.（This error is shown in my attachment）
I finally tried single-ended mapping and got the same result as before, no error but no data either.（This error is shown in my attachment）
It looks like I didn't even get the first step, which is confusing.
I can't solve the problem I'm having, but I do want to use CCMetagen, and if you can help me, I'd really appreciate it.

`(ccmetagen) t010208@bio3-Horsea-12U:~/Chengtao/meta/yuanlab2$ seqkit  stat temp/qc/2017-HB-Ae-aF_1.fastq
file                           format  type    num_seqs        sum_len  min_len  avg_len  max_len
temp/qc/2017-HB-Ae-aF_1.fastq  FASTQ   DNA   10,002,631  1,239,361,408       31    123.9      150
(ccmetagen) t010208@bio3-Horsea-12U:~/Chengtao/meta/yuanlab2$ seqkit  stat temp/qc/2017-HB-Ae-aF_2.fastq
file                           format  type    num_seqs        sum_len  min_len  avg_len  max_len
temp/qc/2017-HB-Ae-aF_2.fastq  FASTQ   DNA   10,002,631  1,221,789,497       31    122.1      150
#(ccmetagen) t010208@bio3-Horsea-12U:~/Chengtao/meta/yuanlab2$ kma -ipe temp/qc/2018-GZ-Ae-p_1.fastq  temp/qc/2018-GZ-Ae-p_2.fastq  temp/kma/2018-GZ-Ae-p_2_kma -t_db /home/data/refdir/database/kraken2/CCMetagen/ncbi_nt_no_env_11jun2019 -t 40 -1t1 -mem_mode -and  -apm f
Uneven number of paired end files.
#I can not understand this error "Uneven number of paired end files".
(ccmetagen) t010208@bio3-Horsea-12U:~/Chengtao/meta/yuanlab2$ kma -i temp/qc/2018-GZ-Ae-p_1.fastq -o temp/kma/2018-GZ-Ae-p_kma -t_db /home/data/refdir/database/kraken2/CCMetagen/ncbi_nt_no_env_11jun2019 -t 30 -1t1 -mem_mode -and
(ccmetagen) t010208@bio3-Horsea-12U:~/Chengtao/meta/yuanlab2$ ls -al  ./temp/kma/
total 16
drwxrwxr-x 2 t010208 t010208 4096 10月 27 01:13 .
drwxrwxr-x 4 t010208 t010208 4096 10月 26 23:18 ..
-rw-rw-r-- 1 t010208 t010208    0 10月 27 01:13 2018-GZ-Ae-p_kma.aln
-rw-rw-r-- 1 t010208 t010208   20 10月 27 01:22 2018-GZ-Ae-p_kma.frag.gz
-rw-rw-r-- 1 t010208 t010208    0 10月 27 01:13 2018-GZ-Ae-p_kma.fsa
-rw-rw-r-- 1 t010208 t010208  129 10月 27 01:22 2018-GZ-Ae-p_kma.res
#No error was reported, but no data was generated`

 
[ccmetagen.txt](https://github.com/vrmarcelino/CCMetagen/files/9872450/ccmetagen.txt)

**Comment by vrmarcelino** [comment]
Hi Tao,

I think you are missing the flag '-o' to indicate the output filepath in KMA.
KMA is complaining about an 'Uneven number of files', not sequences in the files. So I believe KMA is thinking that your output filepath is an additional sequence file. I also think that 40 threads will not make it efficient. Try it with 4 to start:

`kma -ipe temp/qc/2018-GZ-Ae-p_1.fastq temp/qc/2018-GZ-Ae-p_2.fastq -o temp/kma/2018-GZ-Ae-p_2_kma -t_db /home/data/refdir/database/kraken2/CCMetagen/ncbi_nt_no_env_11jun2019 -t 4 -1t1 -mem_mode -and -apm f`

Let me know if it works.

**Comment by TaoCheng98** [comment]
Hi vrmarcelino！

I followed your instructions, but the problem here is just like I mentioned before.
It didn't give an error, but it didn't generate any data either. The result files were empty.

`(ccmetagen) t010208@bio3-Horsea-12U:~/Chengtao/meta/yuanlab2$ kma -ipe temp/qc/2018-GZ-Ae-p_1.fastq temp/qc/2018-GZ-Ae-p_2.fastq -o temp/kma/2018-GZ-Ae-p_2_kma -t_db /home/data/refdir/database/kraken2/CCMetagen/ncbi_nt_no_env_11jun2019 -t 4 -1t1 -mem_mode -and -apm f
Collecting k-mer scores.
 Reading inputfile:	temp/qc/2018-GZ-Ae-p_1.fastq temp/qc/2018-GZ-Ae-p_2.fastq
 Phred scale:	33

 Total time used for DB loading: 139.61 s.

 Finding k-mer ankers

 Total number of query fragment after trimming:	12820422

 Query converted

 Query ankered

 Score collection done
 Sort, output and select k-mer alignments.
 Total time for sorting and outputting KMA alignment	0.18 s.

 Doing local assemblies of found templates, and output results
 Total time used for local assembly: 91.29 s.

 Closing files
(ccmetagen) t010208@bio3-Horsea-12U:~/Chengtao/meta/yuanlab2$ ls -al ./temp/kma/
total 24
drwxrwxr-x 2 t010208 t010208 4096 10月 28 11:10 .
drwxrwxr-x 5 t010208 t010208 4096 10月 27 08:44 ..
-rw-rw-r-- 1 t010208 t010208    0 10月 28 11:10 2018-GZ-Ae-p_2_kma.aln
-rw-rw-r-- 1 t010208 t010208   20 10月 28 11:17 2018-GZ-Ae-p_2_kma.frag.gz
-rw-rw-r-- 1 t010208 t010208    0 10月 28 11:10 2018-GZ-Ae-p_2_kma.fsa
-rw-rw-r-- 1 t010208 t010208  129 10月 28 11:17 2018-GZ-Ae-p_2_kma.res
-rw-rw-r-- 1 t010208 t010208    0 10月 27 01:13 2018-GZ-Ae-p_kma.aln
-rw-rw-r-- 1 t010208 t010208   20 10月 27 01:22 2018-GZ-Ae-p_kma.frag.gz
-rw-rw-r-- 1 t010208 t010208    0 10月 27 01:13 2018-GZ-Ae-p_kma.fsa
-rw-rw-r-- 1 t010208 t010208  129 10月 27 01:22 2018-GZ-Ae-p_kma.res
`

**Comment by vrmarcelino** [comment]
That is strange. Are all KMA files empty?

Could you perhaps try with a different sample for us to identify where the issue is?
(e.g. https://github.com/vrmarcelino/CCMetagen/blob/master/tutorial/figs_tutorial/Subset_bird_data.zip) 

Could you also try updating KMA to the latest version?

It is also possible that there is simply no match between your samples and the database. I think it could happen if the sequencing depth is too shallow and you have very high diversity, or if the same is from a very different environment. What type of samples are you working with? Also - are those raw short-read data?

Thanks!

**Comment by TaoCheng98** [comment]
Hi vrmarcelino！
Sorry for the late reply.
As you suggested, I used the test data to run the program.(e.g. https://github.com/vrmarcelino/CCMetagen/blob/master/tutorial/figs_tutorial/Subset_bird_data.zip)
Unfortunately, I got the same result as before. No errors, no results. And, during that time, I made a friend who had the same problem. Instead of using conda, he followed the installation process as mentioned. And he and I both use the latest KMA, 1.4.7. So, I don't know where our problem is. If you can help us, we will be very grateful to you.
`~/Soft/kma/kma -ipe Avocet_Outback.R1.fastq Avocet_Outback.R2.fastq -o A1_out_kma -t_db /home/data/refdir/database/kraken2/CCMetagen/ncbi_nt_no_env_11jun2019 -t 12 -1t1 -mem_mode -and -apm f`

![3438c3d18a262f6e7bfc21b7328bbb9](https://user-images.githubusercontent.com/85544064/199749151-6c0be242-9521-4a3d-91ad-7d5f6619842a.png)

**Comment by vrmarcelino** [comment]
Hi!
Thanks for this. I haven't come across this issue before.
Could you please try using KMA version 1.3.13? 
It might be a compatibility issue.

Thanks!

**Comment by ptlcc** [comment]
Hi Tao

This looks like an error related to kma. I have tested it with Vanessas suggestion above with different versions of kma, and there is indeed a problem.
I have solved this in version 1.4.8 of kma.

Best,
Philip

**Comment by vrmarcelino** [comment]
Thanks Philip!!
