### ISSUE TITLE
Error with CCMetagen.py

### ISSUE THREAD

**Issue by DrYoungOG** [vrmarcelino/CCMetagen#43]
Hello,  CCMetagen Team! 
Thanks for the excellent software!

Some errors occured which reported "NCBI database not present yet" and "Name or service not known" when run the CCMetagen.py after the completion of the kma alignment step. Please see the attachment for detailed errors.

This is the script used for one of my samples (S0101w0-LED4262_L1 is the sample ID):
CCMetagen.py -i /home/yangpc/YihuoProject_metagenome_analysis/ccmetagen/1.kma_alignment/output/S0101w0-LED4262_L1.res 
-o /home/yangpc/YihuoProject_metagenome_analysis/ccmetagen/2.ccmetagen_py/output 
-map /home/yangpc/YihuoProject_metagenome_analysis/ccmetagen/1.kma_alignment/output/S0101w0-LED4262_L1.mapstat 
--depth_unit fr --depth 1

Background: I installed pandas, ete3, kma, krona, and CCmetagen in one conda virtual environment naned "ccmetagen".

Any help will be appreciated!

Looking forward to your reply.
[CCmetagen_py_error.txt](https://github.com/vrmarcelino/CCMetagen/files/9920178/CCmetagen_py_error.txt)

**Comment by vrmarcelino** [comment]
Hi!

Thanks for getting in touch. It is the first time I see this one.
There seems to be an issue with ETE3 downloading the database (which only needs to happen the first time you use CCMetagen).
Could you try installing and updating the database in your virtual environment? It can take several minutes.

```
python
from ete3 import NCBITaxa
ncbi = NCBITaxa()
ncbi.update_taxonomy_database()
quit()
```

Let me know how it goes.

**Comment by DrYoungOG** [comment]
Thanks for your reply!
The softwore worked well following your instructions.

Once again, my sincere appreciation.

**Comment by vrmarcelino** [comment]
I'm happy to hear that.
Thanks for letting us know!
