### ISSUE TITLE
Permissions error when running the ccmetagen server

### ISSUE THREAD

**Issue by arivers** [vrmarcelino/CCMetagen#5]
When I run a small evaluation file through the [ccmetagen web server](https://cge.cbs.dtu.dk/services/ccmetagen/) I get this error:

```
cp: cannot create regular file `/srv/www/htdocs/services/CCMetagen-1.0/tmp/6_3_1_2020_1025_364_23438.html': Permission denied
```

**Comment by vrmarcelino** [comment]
Thanks for letting us know!
We are following this up and we'll get back to you shortly.

**Comment by vrmarcelino** [comment]
Hi Adam,

Could you try it again and let us know if you have any errors?
There were some issues with the web servers indeed, they should be fixed now.

**Comment by arivers** [comment]
Yes, this fixed the issue.
