### ISSUE TITLE
download the "ncbi_nt_no_env_11jun2019" database error

### ISSUE THREAD

**Issue by HeHan-hub** [vrmarcelino/CCMetagen#50]
Hello.
When I try to download the "ncbi_nt_no_env_11jun2019" database, it keeps prompting me that the file is corrupted and has CRC checksum errors when I decompress it, and I have changed the download tool and decompression tool, but it is still the same, is there any solution?
Thank you!

**Comment by vrmarcelino** [comment]
Hi, 
Apologies for the late reply. We have had issues with the mirrored files being corrupted in cloudstor, so the download would work some times, and not others. So I suspect this is happening again. I am looking into solutions for a new place to store it, but that migth take a few months, sorry.
For now the only thing that migth help is to try again.
I can also help you build your own custom database if that helps.

**Comment by hehanhhh** [comment]
Hello,
Thank you for your reply. Is there any way to speed up building a local database? We are following the tutorial very slowly and it is very memory intensive.
Thank you.

**Comment by HeHan-hub** [comment]
@vrmarcelino  Thank you for your reply. Is there any way to speed up building a local database? We are following the tutorial very slowly and it is very memory intensive.

**Comment by vrmarcelino** [comment]
Hi!
Is this the KMA step? You'd probably need a server with ~500Gb of memory.

**Comment by HeHan-hub** [comment]
@vrmarcelino  Thanks, so far I have successfully downloaded the the "ncbi_nt_no_env_11jun2019" database, but do I need to use the kma index for this file?
If kma index is required, then what file is used as input file?
If kma index is not needed, I use kma -ipe /clusterfs/ZH11_FDSW220008794-2r_1.clean.fq.gz /clusterfs/ZH11_FDSW220008794-2r_2.clean.fq.gz -o /clusterfs/ ZH11_kma -t_db /clusterfs/ncbi_nt_no_env_11jun2019 -t 30 -1t1 -mem_mode -and -apm f -ef testing kma but it stays in running state without outputting results, any solution? Thanks a lot!

**Comment by vrmarcelino** [comment]
Hi!

Great that the download worked!

This database is already indexed so you can proceed directly to the kma mapping step.

How much memory are you giving to KMA? It might be stuck without memory.

I've also noticed some spaces in the command.
I'd also recommend using less cores (4 is usually good).
Assuming you are in a folder where you have another folder called 'clusterfs', maybe try:

`kma -ipe clusterfs/ZH11_FDSW220008794-2r_1.clean.fq.gz clusterfs/ZH11_FDSW220008794-2r_2.clean.fq.gz -o clusterfs/ZH11_kma -t_db clusterfs/ncbi_nt_no_env_11jun2019 -t 4 -1t1 -mem_mode -and -apm f -ef`

**Comment by hehanhhh** [comment]
@vrmarcelino Thanks, it was a memory issue that is now fixed. 
But when I remove -and and -apm f, kma is running but not outputting results, is it necessary to change other parameters?
And when I run CCMetagen.py -i /clusterfs/ZH11-kma.res -o /clusterfs/ -map /clusterfs/ZH11-kma.mapstat -t 4 -ef y, there is : 

Traceback (most recent call last).
  File "/clusterfs/software/miniconda3/envs/ccmetagen/bin/CCMetagen.py", line 136, in <module>
    raise ValueError("If used, the argument taxfile has to point to a taxdump file")
ValueError: If used, the argument taxfile has to point to a taxdump file
How can I solve this? Thank you very much.
