### ISSUE TITLE
Indexing custom database returns empty *.length.b file

### ISSUE THREAD

**Issue by longwayl** [vrmarcelino/CCMetagen#51]
Hi!

I've made a custom database using your instructions (https://github.com/vrmarcelino/CCMetagen/tree/master/benchmarking/rename_nt) and also used your scripts to filter out unwanted taxa (remove_unclassified_from_acc2taxidmap.py and rename_clean_nt.py). Everything appears to be in order, but when I run the indexing command (kma index -i nt_w_taxid.fas -o CCMetagen_ntDatabase_noEnv_2023) the output file "CCMetagen_ntDatabase_noEnv_2023.length.b" is empty. All the other files look alright and the odd thing is that there were no errors in the log files. Do you know what I might have done wrong? Thanks!

Best,
Lucas

**Comment by vrmarcelino** [comment]
Hi Lucas,

Thanks for the initiative of making a new database!  
That is odd. I suspect that the indexing just didn't finish... It is huge database, so you also need the flags ' -NI -Sparse TG'.  This step also requires a lot of memory (˜500Gb I believe). 
Let me know if any of these help.
