### ISSUE TITLE
 /bin/sh: 1: ktImportText: Permission denied

### ISSUE THREAD

**Issue by lichen-fungus** [vrmarcelino/CCMetagen#52]
I am getting this error when running CCMetagen for the first time (kma finished alright):

`python CCMetagen.py -i MyFile_out_kma.res -o results_CCMetagen
`
```
Reading file MyFile_out_kma.res


csv file saved as results_CCMetagen.ccm.csv

/bin/sh: 1: ktImportText: Permission denied
krona file saved as results_CCMetagen.html
```
However, there is no such output "results_CCMetagen.html"

Can you please advise how to solve this problem?

Kind regards

**Comment by vrmarcelino** [comment]
Hi,

I think Krona is not accessible to CCMetagen, or does not have execution permissions.
Could you try editing the permissions of your ktImportText script?
`chmod +x KronaTools-2.7/bin/ktImportText`

**Comment by lichen-fungus** [comment]
Hi, thanks for your help! I started searching for ktImportText in the anaconda3 folder like this  `find envs/ -type f -name ktImportText*` and didn't find ktImportText anywhere, and found out that krona was lacking. I installed krona 2.7.1 with Mamba like below and now it looks like it's working. 
```
conda activate CCMetagen
mamba install krona=2.7.1
```
Kind regards

**Comment by vrmarcelino** [comment]
Ah good to hear that!

Thanks
