### ISSUE TITLE
How much memory does kma require?

### ISSUE THREAD

**Issue by HeHan-hub** [vrmarcelino/CCMetagen#54]
Hello,
Thank you very much for answering my question earlier.
One question I have is how much memory does kma need to run? I have two pairs of sequences in fq format that I have run multiple times and cannot get the output.
So I tried to run kma on my local ubuntu and got :
Error: 12 (Cannot allocate memory), 
but I should have more than enough memory.

**Comment by vrmarcelino** [comment]
Hi,

It depends on the database and flags you are using with kma.
If using the nt database, and the SPARSE and mem mode , then I think 250Gb will run, and 500Gb will definitely be enough.
Which commands are you using to run kma?

**Comment by hehanhhh** [comment]
Hello,
Thank you for your reply.
I should have enough RAM.
I would like to ask you a new question, can ccmetagen get an absolute abundance table for the number of reads? The table I get now seems to be a relative abundance table.
I would like to be able to see how many reads each sample has in a given species.

Like the graph below where the numbers are the number of reads.









3178055041qq.com
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vrmarcelino/CCMetagen"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月8日(星期五) 中午11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vrmarcelino/CCMetagen] How much memory does kma require? (Issue #54)





 
Hi,
 
It depends on the database and flags you are using with kma.
 If using the nt database, and the SPARSE and mem mode , then I think 250Gb will run, and 500Gb will definitely be enough.
 Which commands are you using to run kma?

**Comment by HeHan-hub** [comment]
Hello,
Thank you for your reply.
I should have enough RAM.
I would like to ask you a new question, can ccmetagen get an absolute abundance table for the number of reads? The table I get now seems to be a relative abundance table.
I would like to be able to see how many reads each sample has in a given species.
Like the tabular below where the numbers are the number of reads.

taxa                           B1   B2
Acanthomorphata   736  754
Aculeata                   624  540

**Comment by vrmarcelino** [comment]
Hi
Yes you can get number of reads using the flag '--depth_unit fr'(number of PE reads matching to the reference sequence0>
But to get that you also need to run KMA with the commands.
If you want fragment units, you will need to supply the .mapstats file generated with KMA (which you get when running kma with the flag '-ef').
