### ISSUE TITLE
issues with ete3 calling in CCMetagen.py

### ISSUE THREAD

**Issue by keckstrom** [vrmarcelino/CCMetagen#6]
Hello,

After successfully using CCMetagen for months, on a new run I'm experiencing errors calling the CCMetagen.py script. Everything prior to this point runs smoothly, yet invoking this script returns the error:
ModuleNotFoundError: No module named 'ete3'

I've traced it back to a python error (import: unable to open X server), however after updating, reinstalling, checking the python interpreter, or setting the PATH directly the ete3 installation nothing has helped. I'm wondering if this is something you have experienced all, or if this is simply changes to my university's HPC.

Thanks!
Korin

**Comment by vrmarcelino** [comment]
Hi Korin! Thanks for sharing this issue. I have not seen this error before, but I think the ete3 installation (or its dependencies) did not install or updated correctly.
Do you get the same import error when running `python -c "import ete3"`?
When did you get the python import error exactly? When running CCMetagen or when installing ete3?

**Comment by vrmarcelino** [comment]
I'll close this due to inactivity, feel free to open if the issue persists.
