### ISSUE TITLE
What does --coverage do?

### ISSUE THREAD

**Issue by cabbagesofdoom** [vrmarcelino/CCMetagen#7]
Hi. Sorry if I have missed it, but can you point me to how the minimum coverage (`--coverage`) setting is actually used. I see the default is 20. 20 what? Thanks.

**Comment by vrmarcelino** [comment]
Hi!
Coverage is the percentage of the reference sequence that overlaps (or is ‘covered by’) the consensus alignment. The default is that at least 20% of the reference sequence needs to be covered for it to be considered a match. Note that coverage can be >100, due for example to insertions in the query sequences. I have added an explanation in the readme file and in the code.
