### ISSUE TITLE
Feature request: unmapped/unknown contigs

### ISSUE THREAD

**Issue by cabbagesofdoom** [vrmarcelino/CCMetagen#8]
I am using CCMetagen a bit off-piste and was initially getting confusing results until I realised that most of my sequences do not have any ncbi_nt hits as detected by KMA. These contigs do not seem to appear in the final output, which massively distorts the overall contribution of the taxa that did have hits. Is there a toggle to add an "Unknown" or "Unassigned" taxon to all the sequences without any KMA hits? If not, could you add one? Thanks.

**Comment by vrmarcelino** [comment]
Hi again,
There is no option to calculate the proportion of unclassified reads yet (at least not in a straightforward way). It is on my to-do list and I’ll let you know when it is done.

**Comment by strejcem** [comment]
Hi,
I'd like to support @cabbagesofdoom 's request. I work with vastly undescribed microbiome, e.g. Kraken2 with standard database + fungi classified only ~15%. I tried CCMetagen with nt database and actually human contamination showed to be of 60% of classified reads, which is confusing and not really showing full picture. Recovering MAGs and using GTDB I can say that at least 60% of data are prokaryotes (MAGs 50+ completeness).

Thanks for the tool!

**Comment by vrmarcelino** [comment]
Thanks Michal!
I'll get this feature done.
Considering that prokaryotes are easier to assemble, I expect that many more MAGs would be recovered for proks than for eukaryotes, and that does not necessary reflect the proportion of these organisms in the sample.
But I agree that knowing how many reads were classified will be useful. I'll let you know when this is done.

**Comment by vrmarcelino** [comment]
Hi @strejcem and @cabbagesofdoom,
Following your request, CCMetagen now has an option to output the proportion of classified reads.

In a nutshell: run KMA with the -ef flag, then pass the additional output file (xxx.mapstat) to CCMetagen using the flags ‘-map xxx.mapstat’ and ‘ef y’. This will produce a file that contains the % of classified reads for each template, and the overall % of mapped reads. Please check CCMetagen’s README page for more details.

I also added a script to produce a fasta file containing sequences belonging to a given taxon. @cabbagesofdoom, I recall you mentioning that this feature could be used to filter contaminants from WGS data (I think it will only be useful if complete genomes of the contaminants are present in the reference database though).

We are in the process of updating the PyPI package (will let you know when that is done and then close this issue), but the code is already available here in GitHub.
Let me know if you encounter issues.

**Comment by vrmarcelino** [comment]
The feature is now in the latest CCMetagen version (>1.2.0) in github and in PyPI.
