### ISSUE TITLE
acc2taxid.map

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [vrmarcelino/CCMetagen#9]
Hi,

can you please tell me where to get acc2taxid_map mentioned in rename_nt.py? I need to reformat fasta files to build my own dbs. Alternatively can you tell me the format of the file and I cn make my own from https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_gb.accession2taxid.gz

Thanks,

Theo

**Comment by vrmarcelino** [comment]
Hi!

It is a tab-separated file with 2 columns: accession.version and taxid. From the file you got, you can use cut to get the two columns needed:

`cut -f 2-3 nucl_gb.accession2taxid > accession_taxid_nucl.map`

Hope this helps,
Vanessa

**Comment by vrmarcelino** [comment]
I have added some notes in the rename_nt.py page to clarify the input files:
[https://github.com/vrmarcelino/CCMetagen/tree/master/benchmarking/rename_nt](url)

Note that this script takes as input a sequential fasta file (while the one downloaded from genbank often comes interleaved).
Let me know if you find any issues.
